### ISSUE TITLE
problems timing threadDelay ?

### ISSUE THREAD

**Issue by simonmichael** [merijn/timeit#3]
As a sanity check I tried timing threadDelay. It pauses for the right amount of time, but the results are strangely low. What could explain this ?
```
ghci> import Control.Concurrent
ghci> import System.TimeIt
ghci> timeIt $ threadDelay 1000000
CPU time:   0.00s
ghci> timeIt $ threadDelay 2000000
CPU time:   0.00s
ghci> timeIt $ threadDelay 5000000
CPU time:   0.01s
ghci> timeItT $ threadDelay 1000000
(1.639e-3,())
ghci> timeItT $ threadDelay 2000000
(4.502e-3,())
ghci> timeItT $ threadDelay 5000000
(1.0310999999999999e-2,())
```

**Comment by merijn** [comment]
Lennart's original (i.e. the current) code times *CPU* time, not wallclock time. Since the thread is idle and suspended the CPU time is approximately zero.

I want to revise the module to add some other timing options like wallclock time, but I haven't gotten around to that so far.

**Comment by simonmichael** [comment]
Aha, thank you.
